### ISSUE TITLE
[project-index Page] Translate to Japanese

### ISSUE THREAD

**Issue by manak1** [vue-a11y/vue-a11y.com#46]
## About the post

- [ ] I would like to suggest a topic;
- [x] I would like to write the post/article;

## Category

- [ ] News
- [ ] HTML / Semantic
- [ ] ARIA
- [ ] WCAG
- [ ] Tools / Testing
- [ ] Vue A11y packages / UI libraries
- [ ] Single page app

> None of the above categories? Describe a category that the subject of "post / article" makes the most sense.

- [x] Translate

## Brief description
Translate `jp/project/index.md`  to Japanese.

**Comment by manak1** [comment]
I would like to contribute on this issue!

**Comment by yamanoku** [comment]
@manak1 Please do 👍

**Comment by yamanoku** [comment]
@manak1
If you do the translation work, please also support overwriting the text and the following [Frontmatter](https://vuepress.vuejs.org/guide/frontmatter.html) 😃 

```yaml
title: 日本語翻訳タイトル
description: 日本語翻訳description

meta:
  - property: 'og:image'
    content: 'https://vue-a11y.com/img/social-share-jp.png'
  - name: 'twitter:title'
    content: 日本語翻訳タイトル
  - name: 'twitter:description'
    content: 日本語翻訳description
  - name: 'twitter:image'
    content: 'https://vue-a11y.com/img/social-share-jp.png'
```
